# Generated by Django 2.1.3 on 2020-07-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='ref/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='ref/covers/')),
            ],
        ),
    ]
